import 'package:flutter/material.dart';

class AppStrings {
  static Map<String, Map<String, String>> localizedValues = {
    'en': {
      'attendance': 'Attendance',
      'fees_collection': 'Fees Collection',
      'deposit_fee': 'Deposit Fee',
      'pending_fee': 'Pending Fee',
      'time_table': 'Time Table',
      'assignment': 'Assignment',
      'exam_result': 'Exam Result',
      'Notices':'Notices',
      'Events': 'Events',
      'student_profile': 'Student Profile',
      'language': 'Language',
      'change_password': 'Change Password',
      'logout': 'Logout',
      'logout_confirm': 'Are you sure you want to logout?',
      'cancel': 'Cancel',
      'selected_date': 'Selected Date',
      'holiday': 'Holiday',
      'present': 'Present',
      'absent': 'Absent',
      'leave': 'Leave',
      'no_record': 'No Record',
      'current_password': 'Current password',
      'new_password': 'New password',
      'confirm_password': 'Retype new password',
      'enter_old_password': 'Enter your old password',
      'password_min': 'Password must be at least 6 characters',
      'password_not_match': 'Passwords do not match',
      'confirm_change': 'Confirm Change',
      'password_success': 'Password changed successfully',
      'enter_password': 'Enter Password',
      'password_hint': 'Your password must be at least 6 characters and should include a combination of numbers, letters and special characters (!\$@%).',
      'no_data': 'No Data Found',
      'paid': 'Paid',
      'pending': 'Pending',
      'total': 'Total',
      'balance': 'Balance',
      'total_fee': 'Total Fee',
      'total_paid': 'Total Paid',
      'total_balance': 'Total Balance',
      'edit_profile': 'Edit Profile',
      'take_photo': 'Take Photo',
      'choose_gallery': 'Choose from Gallery',
      'enter_contact': 'Enter Contact Number',
      'saved_success': 'Saved Successfully',
      'contact_number': 'Contact Number',
      'save_changes': 'Save Changes',
      'select_month': 'Select Month Range',
      'admission_no': 'Admission No',
      'date': 'Date',
      'student_name': 'Student Name',
      'father_name': "Father's Name",
      'class': 'Class',
      'section': 'Section',
      'fees_head': 'Fees Head',
      'total_actual': 'Total Actual',
      'no_fee_data': 'No fee details found.',
      'all_paid': 'All fees paid for this session.',
      'pay': 'Pay',
      'payment_error': 'Payment gateway not found',
      'previous_balance': 'Previous Balance',
      'total_payable': 'Total Payable',
      'feedback': 'Feedback',
      'title': 'Title',
      'description': 'Description',
      'enter_title': 'Please enter title',
      'enter_description': 'Please enter description',
      'submit_feedback': 'Submit Feedback',
      'view_feedback': 'View Feedback',
      'feedback_success': 'Feedback Submitted Successfully',
      'something_went_wrong': 'Something went wrong',
      'no_feedback_found': 'No Feedback Found',
      'student_id': 'Student ID',
      'remark': 'Remark',
      'event': 'Event',
      'no_events': 'No Events',
      'upcoming_classes': 'Upcoming Classes',
      'view_all': 'View All',
      'home': 'Home',
      'notification': 'Notification',
      'profile': 'Profile',
      'my_classes': 'My Classes',
      'no_data_available': 'No Data Available',

      'monday': 'MON',
      'tuesday': 'TUE',
      'wednesday': 'WED',
      'thursday': 'THU',
      'friday': 'FRI',
      'saturday': 'SAT',
    },

    'hi': {
      'attendance': 'उपस्थिति',
      'fees_collection': 'फीस संग्रह',
      'deposit_fee': 'फीस जमा करें',
      'pending_fee': 'लंबित फीस',
      'time_table': 'समय सारणी',
      'assignment': 'कार्य',
      'exam_result': 'परीक्षा परिणाम',
      'Notices': 'समाचार',
      'Events': 'आयोजर',
      'student_profile': 'छात्र प्रोफ़ाइल',
      'language': 'भाषा',
      'change_password': 'पासवर्ड बदलें',
      'logout': 'लॉगआउट',
      'logout_confirm': 'क्या आप वाकई लॉगआउट करना चाहते हैं?',
      'cancel': 'रद्द करें',
      'selected_date': 'चयनित तिथि',
      'holiday': 'छुट्टी',
      'present': 'उपस्थित',
      'absent': 'अनुपस्थित',
      'leave': 'अवकाश',
      'no_record': 'कोई रिकॉर्ड नहीं',
      'current_password': 'वर्तमान पासवर्ड',
      'new_password': 'नया पासवर्ड',
      'confirm_password': 'पासवर्ड पुनः दर्ज करें',
      'enter_old_password': 'अपना पुराना पासवर्ड दर्ज करें',
      'password_min': 'पासवर्ड कम से कम 6 अक्षरों का होना चाहिए',
      'password_not_match': 'पासवर्ड मेल नहीं खाते',
      'confirm_change': 'परिवर्तन की पुष्टि करें',
      'password_success': 'पासवर्ड सफलतापूर्वक बदल दिया गया',
      'enter_password': 'पासवर्ड दर्ज करें',
      'password_hint': 'आपका पासवर्ड कम से कम 6 अक्षरों का होना चाहिए और इसमें संख्या, अक्षर और विशेष चिन्ह (!\$@%) शामिल होने चाहिए।',
      'no_data': 'कोई डेटा नहीं मिला',
      'paid': 'जमा',
      'pending': 'लंबित',
      'total': 'कुल',
      'balance': 'शेष',
      'total_fee': 'कुल फीस',
      'total_paid': 'कुल जमा',
      'total_balance': 'कुल शेष',
      'edit_profile': 'प्रोफ़ाइल संपादित करें',
      'take_photo': 'फोटो लें',
      'choose_gallery': 'गैलरी से चुनें',
      'enter_contact': 'संपर्क नंबर दर्ज करें',
      'saved_success': 'सफलतापूर्वक सहेजा गया',
      'contact_number': 'संपर्क नंबर',
      'save_changes': 'परिवर्तन सहेजें',
      'select_month': 'महीना चुनें',
      'admission_no': 'प्रवेश संख्या',
      'date': 'तारीख',
      'student_name': 'छात्र का नाम',
      'father_name': 'पिता का नाम',
      'class': 'कक्षा',
      'section': 'अनुभाग',
      'fees_head': 'फीस शीर्षक',
      'total_actual': 'कुल वास्तविक',
      'no_fee_data': 'कोई फीस विवरण नहीं मिला',
      'all_paid': 'इस सत्र की सभी फीस जमा हो चुकी है',
      'pay': 'भुगतान करें',
      'payment_error': 'पेमेंट गेटवे उपलब्ध नहीं है',
      'previous_balance': 'पिछला बकाया',
      'total_payable': 'कुल देय राशि',
      'feedback': 'प्रतिक्रिया',
      'title': 'शीर्षक',
      'description': 'विवरण',
      'enter_title': 'कृपया शीर्षक दर्ज करें',
      'enter_description': 'कृपया विवरण दर्ज करें',
      'submit_feedback': 'प्रतिक्रिया भेजें',
      'view_feedback': 'प्रतिक्रिया देखें',
      'feedback_success': 'प्रतिक्रिया सफलतापूर्वक भेजी गई',
      'something_went_wrong': 'कुछ गलत हो गया',
      'no_feedback_found': 'कोई प्रतिक्रिया नहीं मिली',
      'student_id': 'छात्र आईडी',
      'remark': 'टिप्पणी',
      'event': 'कार्यक्रम',
      'no_events': 'कोई कार्यक्रम नहीं',
      'upcoming_classes': 'आगामी कक्षाएं',
      'view_all': 'सभी देखें',
      'home': 'होम',
      'notification': 'सूचनाएं',
      'profile': 'प्रोफ़ाइल',
      'my_classes': 'मेरी कक्षाएं',
      'no_data_available': 'कोई डेटा उपलब्ध नहीं',

      'monday': 'सोम',
      'tuesday': 'मंगल',
      'wednesday': 'बुध',
      'thursday': 'गुरु',
      'friday': 'शुक्र',
      'saturday': 'शनि',
    },
  };

  static String get(BuildContext context, String key) {
    final langCode = Localizations.localeOf(context).languageCode;
    return localizedValues[langCode]?[key] ?? key;
  }
}
